-- Program 1: Vypocet faktorialu (iterativne)
require "ifj21"

function main() -- uzivatelska funkce bez parametru
  local a : integer
  local vysl : integer = e
  --write("Zadejte cislo pro vypocet faktorialu\n")
  a = e
  if e then
      --write("a je nil\n") return
  else
  end
  if e then
    --write("Faktorial nelze spocitat\n")
  else
    vysl = e
    while e do
      vysl = e a = e  -- dva prikazy
    end
    --[[write("Vysledek je:  ", vysl, "\n")]]
  end
end

--main()  